@startuml esp8266
!includeurl https://gist.githubusercontent.com/anoff/c531251183cf9590b0f86ac85d5bc353/raw/fancy.plantuml
start
@startuml


entity "Car" as car {

  *id : int <<primary key>>

  --

  *last_updated : timestamp with time zone

  make : string

  model : string

  year : int

}


entity "Factory" as factory {

  *id : int <<primary key>>

  --

  *country : string

}


entity "Factory Car Support" as factoryCarSupport {

  *id: int <<primary key>>

  --

  factory : int <<FK>>

  car : int <<FK>>

}


factoryCarSupport ||..o{ factory

factoryCarSupport |o..o{ car


@enduml
end
@enduml
