@startuml


entity "Post Box" as amenity=post_box {

  *id : int <<primary key>>
  --
  * geolocation : geodata
  *last_updated : timestamp with time zone
}

entity "Postal Collection Service" as service=postal_collection {

  *id : int <<primary key>>
  --
  ref : string <<unique key>>
  collection_times : string
  operator : string
}

entity "Physical Post Box" as man_made=post_box {

  *id : int <<primary key>>
  --
  ref : string <<unique key>>
  
  }

amenity=post_box ||..o| service=postal_collection

amenity=post_box |o..o| man_made=post_box

@enduml
