@startuml


entity "Post Box" as amenity=post_box {

  *id : int <<primary key>>
  --
  *last_updated : timestamp with time zone
  *geolocation : int
 "post_box:type" : string
  ref : string
  collection_times : string
  operator : string
  blbbla : string
}

@enduml
