@startuml


entity "Post Box" as amenity=post_box {

  *id : int <<primary key>>
  --
  * geolocation: geodata
  *last_updated : timestamp with time zone
  "post_box:type" : string
  ref : string
  collection_times : string
  operator : string
}

@enduml
